export * from "./header/SideBar4";
export * from "./header/Header";
export * from "./footer/Footer";
export * from "./main/MovieCard";
export * from "./Spinner";
export * from "./details/Trailer";
export * from "./details/ModalComponent";
export * from "./main/DashboardRow";
export * from "./main/Icons"